// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pyre.proto

package pyre

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthorizeAccountRequest struct {
	Authorization        string   `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizeAccountRequest) Reset()         { *m = AuthorizeAccountRequest{} }
func (m *AuthorizeAccountRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizeAccountRequest) ProtoMessage()    {}
func (*AuthorizeAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pyre_effe9a0c8980d636, []int{0}
}
func (m *AuthorizeAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeAccountRequest.Unmarshal(m, b)
}
func (m *AuthorizeAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeAccountRequest.Marshal(b, m, deterministic)
}
func (dst *AuthorizeAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeAccountRequest.Merge(dst, src)
}
func (m *AuthorizeAccountRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizeAccountRequest.Size(m)
}
func (m *AuthorizeAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeAccountRequest proto.InternalMessageInfo

func (m *AuthorizeAccountRequest) GetAuthorization() string {
	if m != nil {
		return m.Authorization
	}
	return ""
}

type AuthorizeAccountResponse struct {
	AccountId               string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AuthorizationToken      string   `protobuf:"bytes,2,opt,name=authorization_token,json=authorizationToken,proto3" json:"authorization_token,omitempty"`
	ApiUrl                  string   `protobuf:"bytes,3,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`
	DownloadUrl             string   `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	RecommendedPartSize     int64    `protobuf:"varint,5,opt,name=recommended_part_size,json=recommendedPartSize,proto3" json:"recommended_part_size,omitempty"`
	AbsoluteMininumPartSize int64    `protobuf:"varint,6,opt,name=absolute_mininum_part_size,json=absoluteMininumPartSize,proto3" json:"absolute_mininum_part_size,omitempty"`
	MinimumPartSize         int64    `protobuf:"varint,7,opt,name=minimum_part_size,json=minimumPartSize,proto3" json:"minimum_part_size,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *AuthorizeAccountResponse) Reset()         { *m = AuthorizeAccountResponse{} }
func (m *AuthorizeAccountResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizeAccountResponse) ProtoMessage()    {}
func (*AuthorizeAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pyre_effe9a0c8980d636, []int{1}
}
func (m *AuthorizeAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeAccountResponse.Unmarshal(m, b)
}
func (m *AuthorizeAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeAccountResponse.Marshal(b, m, deterministic)
}
func (dst *AuthorizeAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeAccountResponse.Merge(dst, src)
}
func (m *AuthorizeAccountResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizeAccountResponse.Size(m)
}
func (m *AuthorizeAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeAccountResponse proto.InternalMessageInfo

func (m *AuthorizeAccountResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *AuthorizeAccountResponse) GetAuthorizationToken() string {
	if m != nil {
		return m.AuthorizationToken
	}
	return ""
}

func (m *AuthorizeAccountResponse) GetApiUrl() string {
	if m != nil {
		return m.ApiUrl
	}
	return ""
}

func (m *AuthorizeAccountResponse) GetDownloadUrl() string {
	if m != nil {
		return m.DownloadUrl
	}
	return ""
}

func (m *AuthorizeAccountResponse) GetRecommendedPartSize() int64 {
	if m != nil {
		return m.RecommendedPartSize
	}
	return 0
}

func (m *AuthorizeAccountResponse) GetAbsoluteMininumPartSize() int64 {
	if m != nil {
		return m.AbsoluteMininumPartSize
	}
	return 0
}

func (m *AuthorizeAccountResponse) GetMinimumPartSize() int64 {
	if m != nil {
		return m.MinimumPartSize
	}
	return 0
}

type GetUploadUrlRequest struct {
	BucketId             string   `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUploadUrlRequest) Reset()         { *m = GetUploadUrlRequest{} }
func (m *GetUploadUrlRequest) String() string { return proto.CompactTextString(m) }
func (*GetUploadUrlRequest) ProtoMessage()    {}
func (*GetUploadUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pyre_effe9a0c8980d636, []int{2}
}
func (m *GetUploadUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUploadUrlRequest.Unmarshal(m, b)
}
func (m *GetUploadUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUploadUrlRequest.Marshal(b, m, deterministic)
}
func (dst *GetUploadUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadUrlRequest.Merge(dst, src)
}
func (m *GetUploadUrlRequest) XXX_Size() int {
	return xxx_messageInfo_GetUploadUrlRequest.Size(m)
}
func (m *GetUploadUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadUrlRequest proto.InternalMessageInfo

func (m *GetUploadUrlRequest) GetBucketId() string {
	if m != nil {
		return m.BucketId
	}
	return ""
}

type GetUploadUrlResponse struct {
	BucketId             string   `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	UploadUrl            string   `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	AuthorizationToken   string   `protobuf:"bytes,3,opt,name=authorization_token,json=authorizationToken,proto3" json:"authorization_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUploadUrlResponse) Reset()         { *m = GetUploadUrlResponse{} }
func (m *GetUploadUrlResponse) String() string { return proto.CompactTextString(m) }
func (*GetUploadUrlResponse) ProtoMessage()    {}
func (*GetUploadUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pyre_effe9a0c8980d636, []int{3}
}
func (m *GetUploadUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUploadUrlResponse.Unmarshal(m, b)
}
func (m *GetUploadUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUploadUrlResponse.Marshal(b, m, deterministic)
}
func (dst *GetUploadUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadUrlResponse.Merge(dst, src)
}
func (m *GetUploadUrlResponse) XXX_Size() int {
	return xxx_messageInfo_GetUploadUrlResponse.Size(m)
}
func (m *GetUploadUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadUrlResponse proto.InternalMessageInfo

func (m *GetUploadUrlResponse) GetBucketId() string {
	if m != nil {
		return m.BucketId
	}
	return ""
}

func (m *GetUploadUrlResponse) GetUploadUrl() string {
	if m != nil {
		return m.UploadUrl
	}
	return ""
}

func (m *GetUploadUrlResponse) GetAuthorizationToken() string {
	if m != nil {
		return m.AuthorizationToken
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthorizeAccountRequest)(nil), "pyre.AuthorizeAccountRequest")
	proto.RegisterType((*AuthorizeAccountResponse)(nil), "pyre.AuthorizeAccountResponse")
	proto.RegisterType((*GetUploadUrlRequest)(nil), "pyre.GetUploadUrlRequest")
	proto.RegisterType((*GetUploadUrlResponse)(nil), "pyre.GetUploadUrlResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PyreServiceClient is the client API for PyreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PyreServiceClient interface {
	AuthorizeAccount(ctx context.Context, in *AuthorizeAccountRequest, opts ...grpc.CallOption) (*AuthorizeAccountResponse, error)
	GetUploadUrl(ctx context.Context, in *GetUploadUrlRequest, opts ...grpc.CallOption) (*GetUploadUrlResponse, error)
}

type pyreServiceClient struct {
	cc *grpc.ClientConn
}

func NewPyreServiceClient(cc *grpc.ClientConn) PyreServiceClient {
	return &pyreServiceClient{cc}
}

func (c *pyreServiceClient) AuthorizeAccount(ctx context.Context, in *AuthorizeAccountRequest, opts ...grpc.CallOption) (*AuthorizeAccountResponse, error) {
	out := new(AuthorizeAccountResponse)
	err := c.cc.Invoke(ctx, "/pyre.PyreService/AuthorizeAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pyreServiceClient) GetUploadUrl(ctx context.Context, in *GetUploadUrlRequest, opts ...grpc.CallOption) (*GetUploadUrlResponse, error) {
	out := new(GetUploadUrlResponse)
	err := c.cc.Invoke(ctx, "/pyre.PyreService/GetUploadUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PyreServiceServer is the server API for PyreService service.
type PyreServiceServer interface {
	AuthorizeAccount(context.Context, *AuthorizeAccountRequest) (*AuthorizeAccountResponse, error)
	GetUploadUrl(context.Context, *GetUploadUrlRequest) (*GetUploadUrlResponse, error)
}

func RegisterPyreServiceServer(s *grpc.Server, srv PyreServiceServer) {
	s.RegisterService(&_PyreService_serviceDesc, srv)
}

func _PyreService_AuthorizeAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyreServiceServer).AuthorizeAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pyre.PyreService/AuthorizeAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyreServiceServer).AuthorizeAccount(ctx, req.(*AuthorizeAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PyreService_GetUploadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyreServiceServer).GetUploadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pyre.PyreService/GetUploadUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyreServiceServer).GetUploadUrl(ctx, req.(*GetUploadUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PyreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pyre.PyreService",
	HandlerType: (*PyreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeAccount",
			Handler:    _PyreService_AuthorizeAccount_Handler,
		},
		{
			MethodName: "GetUploadUrl",
			Handler:    _PyreService_GetUploadUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pyre.proto",
}

func init() { proto.RegisterFile("pyre.proto", fileDescriptor_pyre_effe9a0c8980d636) }

var fileDescriptor_pyre_effe9a0c8980d636 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0x95, 0xdd, 0xb2, 0x65, 0xa7, 0x45, 0x80, 0x17, 0xb4, 0x21, 0xa5, 0xd5, 0x12, 0x21,
	0x54, 0xf5, 0xd0, 0x88, 0x70, 0x83, 0x03, 0xea, 0x09, 0xf5, 0x80, 0x54, 0x6d, 0xe9, 0xd9, 0x72,
	0x92, 0xd1, 0x62, 0x35, 0xb1, 0x8d, 0x63, 0x17, 0xed, 0x1e, 0xe1, 0x11, 0x78, 0x24, 0x1e, 0x81,
	0x57, 0xe0, 0x1d, 0xb8, 0xa2, 0x38, 0x49, 0x49, 0x60, 0xc3, 0x2d, 0x9a, 0xff, 0xff, 0xc6, 0xce,
	0x3f, 0x63, 0x00, 0xb5, 0xd6, 0x78, 0xaa, 0xb4, 0x34, 0x92, 0xec, 0x54, 0xdf, 0xc1, 0xd3, 0x95,
	0x94, 0xab, 0x1c, 0x23, 0xa6, 0x78, 0xc4, 0x84, 0x90, 0x86, 0x19, 0x2e, 0x45, 0x59, 0x7b, 0xc2,
	0xb7, 0x30, 0x3f, 0xb3, 0xe6, 0xa3, 0xd4, 0x7c, 0x83, 0x67, 0x69, 0x2a, 0xad, 0x30, 0x4b, 0xfc,
	0x64, 0xb1, 0x34, 0xe4, 0x39, 0xdc, 0x63, 0x8d, 0xe4, 0x10, 0xdf, 0x5b, 0x78, 0xc7, 0xd3, 0x65,
	0xbf, 0x18, 0x7e, 0x1f, 0x81, 0xff, 0x6f, 0x87, 0x52, 0x49, 0x51, 0x22, 0x39, 0x04, 0x60, 0x75,
	0x89, 0xf2, 0xac, 0xe1, 0xa7, 0x4d, 0xe5, 0x3c, 0x23, 0x11, 0xcc, 0x7a, 0xcd, 0xa8, 0x91, 0xd7,
	0x28, 0xfc, 0x91, 0xf3, 0x91, 0x9e, 0xf4, 0xa1, 0x52, 0xc8, 0x1c, 0x76, 0x99, 0xe2, 0xd4, 0xea,
	0xdc, 0x1f, 0x3b, 0xd3, 0x84, 0x29, 0x7e, 0xa5, 0x73, 0xf2, 0x0c, 0xf6, 0x33, 0xf9, 0x59, 0xe4,
	0x92, 0x65, 0x4e, 0xdd, 0x71, 0xea, 0x5e, 0x5b, 0xab, 0x2c, 0x31, 0x3c, 0xd6, 0x98, 0xca, 0xa2,
	0x40, 0x91, 0x61, 0x46, 0x15, 0xd3, 0x86, 0x96, 0x7c, 0x83, 0xfe, 0x9d, 0x85, 0x77, 0x3c, 0x5e,
	0xce, 0x3a, 0xe2, 0x05, 0xd3, 0xe6, 0x92, 0x6f, 0x90, 0xbc, 0x81, 0x80, 0x25, 0xa5, 0xcc, 0xad,
	0x41, 0x5a, 0x70, 0xc1, 0x85, 0x2d, 0x3a, 0xe0, 0xc4, 0x81, 0xf3, 0xd6, 0xf1, 0xbe, 0x36, 0xdc,
	0xc2, 0x27, 0xf0, 0xb0, 0x62, 0x8a, 0x1e, 0xb3, 0xeb, 0x98, 0xfb, 0x8d, 0xd0, 0x7a, 0xc3, 0x18,
	0x66, 0xef, 0xd0, 0x5c, 0xa9, 0xe6, 0xb2, 0xed, 0x08, 0x0e, 0x60, 0x9a, 0xd8, 0xf4, 0x1a, 0x3b,
	0xf1, 0xdd, 0xad, 0x0b, 0xe7, 0x59, 0xf8, 0xd5, 0x83, 0x47, 0x7d, 0xa8, 0x49, 0xfd, 0x7f, 0x54,
	0x35, 0x12, 0xab, 0x6e, 0x73, 0xaa, 0xa3, 0x9e, 0xda, 0xb6, 0xc7, 0xd0, 0x48, 0xc6, 0x43, 0x23,
	0x89, 0x7f, 0x79, 0xb0, 0x77, 0xb1, 0xd6, 0x78, 0x89, 0xfa, 0x86, 0xa7, 0x48, 0xd6, 0xf0, 0xe0,
	0xef, 0x75, 0x20, 0x87, 0xa7, 0x6e, 0x2b, 0x07, 0x16, 0x2d, 0x38, 0x1a, 0x92, 0xeb, 0xff, 0x09,
	0x5f, 0x7c, 0xf9, 0xf1, 0xf3, 0xdb, 0x68, 0x41, 0x8e, 0xa2, 0x24, 0xae, 0xb6, 0xf8, 0xe6, 0x65,
	0x94, 0xc4, 0xb4, 0xbd, 0x0b, 0xd2, 0x66, 0xa1, 0x48, 0x01, 0xfb, 0xdd, 0x3c, 0xc8, 0x93, 0xba,
	0xef, 0x96, 0x60, 0x83, 0x60, 0x9b, 0xd4, 0x3f, 0x2e, 0x3c, 0xe8, 0x1d, 0xb7, 0x42, 0x43, 0xff,
	0x04, 0xf7, 0xda, 0x3b, 0x49, 0x26, 0xee, 0x05, 0xbd, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xac,
	0x22, 0x90, 0xef, 0x73, 0x03, 0x00, 0x00,
}
